version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - singlelink
  singlelink-server:
    image: neutroncreative/singlelink-server:latest
    build:
      context: server
      dockerfile: server.Dockerfile
    environment:
      - DATABASE
      - SECRET
      - CAPTURE_KEY
      - HOST
      - PORT
      - API_DOMAIN
      - CLIENT_DOMAIN
      - CONTACT_EMAIL
      - AWS_SENDER_EMAIL_ADDRESS
      - AWS_REGION
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - S3_ENDPOINT
      - S3_BUCKETNAME
      - S3_PORT
      - S3_USE_SSL
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - MIXPANEL_TOKEN
      - DELETE_ADDON_INSTALLS_THRESHOLD
    ports:
      - "5566:80"
    networks:
      - singlelink
  singlelink-editor:
    image: neutroncreative/singlelink-editor:latest
    build:
      context: client
      dockerfile: client.Dockerfile
      args:
        API_URL: "http://localhost:5566/"
    depends_on:
      - singlelink-server
    environment:
      - HOSTNAME
      - API_URL="http://singlelink-server/"
    ports:
      - "8080:80"
    networks:
      - singlelink

networks:
  singlelink:
